name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide steps and a minimal reproduction if possible
  - type: input
    attributes:
      label: URL / Route
  - type: textarea
    attributes:
      label: Logs / Screenshots
